language: generic
sudo: required
services:
  -docker

before_install:
 # - docker build -t adamhats/complex-client -f ./client/Dockerfile.dev ./client

script:
#  - docker run -e CI=true adamhats/complex-client npm run test

after_success:
  #- docker build -t adamhats/complex-client-prod ./client
  - docker build -t adamhats/complex-server ./server
  - docker build -t adamhats/complex-nginx ./nginx
  - docker build -t adamhats/complex-worker ./worker

  # log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
  # take images and push to docker
  #- docker push adamhats/complex-client-prod:0.0.1
  - docker ps -a
  - docker pull -a adamhats/complex-server
  - docker tag adamhats/complex-server adamhats/complex-server:latest
  - docker push adamhats/complex-server
  - docker push adamhats/complex-nginx:0.0.1
  - docker push adamhats/complex-worker:0.0.1
    